"""add medicins model

Revision ID: 15654fbef3e1
Revises: 
Create Date: 2026-01-04 13:07:13.451769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15654fbef3e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_commercial', sa.String(length=120), nullable=False),
    sa.Column('nom_scientifique', sa.String(length=120), nullable=False),
    sa.Column('molecule', sa.String(length=120), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('forme', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom_scientifique', 'dosage', 'forme', name='uq_medicament_identity')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicaments')
    # ### end Alembic commands ###
