"""fournisseur achat stock

Revision ID: a3f8698976de
Revises: 15654fbef3e1
Create Date: 2026-01-04 13:22:24.688128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f8698976de'
down_revision = '15654fbef3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fournisseurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('achats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=False),
    sa.Column('date_achat', sa.Date(), nullable=False),
    sa.Column('numero_facture', sa.String(length=100), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicament_id', sa.Integer(), nullable=False),
    sa.Column('lot', sa.String(length=100), nullable=False),
    sa.Column('quantite_restante', sa.Integer(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('prix_achat', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medicament_id'], ['medicaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicament_id', 'lot', name='uq_medicament_lot')
    )
    op.create_table('achat_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achat_id', sa.Integer(), nullable=False),
    sa.Column('medicament_id', sa.Integer(), nullable=False),
    sa.Column('lot', sa.String(length=100), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['achat_id'], ['achats.id'], ),
    sa.ForeignKeyConstraint(['medicament_id'], ['medicaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achat_items')
    op.drop_table('stock_lots')
    op.drop_table('achats')
    op.drop_table('fournisseurs')
    # ### end Alembic commands ###
