"""vente

Revision ID: fbf8cdf3783b
Revises: a3f8698976de
Create Date: 2026-01-04 16:14:14.762551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf8cdf3783b'
down_revision = 'a3f8698976de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_vente', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('benefice', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vente_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vente_id', sa.Integer(), nullable=False),
    sa.Column('medicament_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_achat_moyen', sa.Float(), nullable=False),
    sa.Column('marge_pourcentage', sa.Float(), nullable=False),
    sa.Column('prix_vente_unitaire', sa.Float(), nullable=False),
    sa.Column('total_ligne', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['medicament_id'], ['medicaments.id'], ),
    sa.ForeignKeyConstraint(['vente_id'], ['ventes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vente_items')
    op.drop_table('ventes')
    # ### end Alembic commands ###
